/**
 * Holds metadata about all episodes, mapped to each season.
 */
export const episodes: { [season: number]: { [episode: number]: { name: string } } } = {
  1: {
    1: { name: "Cartman Gets an Anal Probe" },
    2: { name: "Weight Gain 4000" },
    3: { name: "Volcano" },
    4: { name: "Big Gay Al's Big Gay Boat Ride" },
    5: { name: "An Elephant Makes Love to a Pig" },
    6: { name: "Death" },
    7: { name: "Pinkeye" },
    8: { name: "Starvin' Marvin" },
    9: { name: "Mr. Hankey, the Christmas Poo" },
    10: { name: "Damien" },
    11: { name: "Tom's Rhinoplasty" },
    12: { name: "Mecha-Streisand" },
    13: { name: "Cartman's Mom Is a Dirty Slut" },
  }, 2: {
    1: { name: "Terrance and Phillip in Not Without My Anus" },
    2: { name: "Cartman's Mom Is Still a Dirty Slut" },
    3: { name: "Ike's Wee Wee" },
    4: { name: "Chickenlover" },
    5: { name: "Conjoined Fetus Lady" },
    6: { name: "The Mexican Staring Frog of Southern Sri Lanka" },
    7: { name: "City on the Edge of Forever" },
    8: { name: "Summer Sucks" },
    9: { name: "Chef's Chocolate Salty Balls" },
    10: { name: "Chickenpox" },
    11: { name: "Roger Ebert Should Lay Off the Fatty Foods" },
    12: { name: "Clubhouses" },
    13: { name: "Cow Days" },
    14: { name: "Chef Aid" },
    15: { name: "Spookyfish" },
    16: { name: "Merry Christmas, Charlie Manson!" },
    17: { name: "Gnomes" },
    18: { name: "Prehistoric Ice Man" },
  }, 3: {
    1: { name: "Rainforest Shmainforest" },
    2: { name: "Spontaneous Combustion" },
    3: { name: "The Succubus" },
    4: { name: "Jakovasaurs" },
    5: { name: "Tweek vs. Craig" },
    6: { name: "Sexual Harassment Panda" },
    7: { name: "Cat Orgy" },
    8: { name: "Two Guys Naked in a Hot Tub" },
    9: { name: "Jewbilee" },
    10: { name: "Korn's Groovy Pirate Ghost Mystery" },
    11: { name: "Chinpokomon" },
    12: { name: "Hooked on Monkey Fonics" },
    13: { name: "Starvin' Marvin in Space" },
    14: { name: "The Red Badge of Gayness" },
    15: { name: "Mr. Hankey's Christmas Classics" },
    16: { name: "Are You There God? It's Me, Jesus" },
    17: { name: "World Wide Recorder Concert" },
  }, 4: {
    1: { name: "The Tooth Fairy's Tats 2000" },
    2: { name: "Cartman's Silly Hate Crime 2000" },
    3: { name: "Timmy 2000" },
    4: { name: "Quintuplets 2000" },
    5: { name: "Cartman Joins NAMBLA" },
    6: { name: "Cherokee Hair Tampons" },
    7: { name: "Chef Goes Nanners" },
    8: { name: "Something You Can Do with Your Finger" },
    9: { name: "Do the Handicapped Go to Hell?" },
    10: { name: "Probably" },
    11: { name: "4th Grade" },
    12: { name: "Trapper Keeper" },
    13: { name: "Helen Keller! The Musical" },
    14: { name: "Pip" },
    15: { name: "Fat Camp" },
    16: { name: "The Wacky Molestation Adventure" },
    17: { name: "A Very Crappy Christmas" },
  }, 5: {
    1: { name: "It Hits the Fan" },
    2: { name: "Cripple Fight" },
    3: { name: "Super Best Friends" },
    4: { name: "Scott Tenorman Must Die" },
    5: { name: "Terrance and Phillip: Behind the Blow" },
    6: { name: "Cartmanland" },
    7: { name: "Proper Condom Use" },
    8: { name: "Towelie" },
    9: { name: "Osama bin Laden Has Farty Pants" },
    10: { name: "How to Eat with Your Butt" },
    11: { name: "The Entity" },
    12: { name: "Here Comes the Neighborhood" },
    13: { name: "Kenny Dies" },
    14: { name: "Butters' Very Own Episode" },
  }, 6: {
    1: { name: "Jared Has Aides" },
    2: { name: "Asspen" },
    3: { name: "Freak Strike" },
    4: { name: "Fun with Veal" },
    5: { name: "The New Terrance and Phillip Movie Trailer" },
    6: { name: "Professor Chaos" },
    7: { name: "Simpsons Already Did It" },
    8: { name: "Red Hot Catholic Love" },
    9: { name: "Free Hat" },
    10: { name: "Bebe's Boobs Destroy Society" },
    11: { name: "Child Abduction Is Not Funny" },
    12: { name: "A Ladder to Heaven" },
    13: { name: "The Return of the Fellowship of the Ring to the Two Towers" },
    14: { name: "The Death Camp of Tolerance" },
    15: { name: "The Biggest Douche in the Universe" },
    16: { name: "My Future Self 'n' Me" },
    17: { name: "Red Sleigh Down" },
  }, 7: {
    1: { name: "Cancelled" },
    2: { name: "Krazy Kripples" },
    3: { name: "Toilet Paper" },
    4: { name: "I'm a Little Bit Country" },
    5: { name: "Fat Butt and Pancake Head" },
    6: { name: "Lil' Crime Stoppers" },
    7: { name: "Red Man's Greed" },
    8: { name: "South Park Is Gay" },
    9: { name: "Christian Rock Hard" },
    10: { name: "Grey Dawn" },
    11: { name: "Casa Bonita" },
    12: { name: "All About Mormons" },
    13: { name: "Butt Out" },
    14: { name: "Raisins" },
    15: { name: "It's Christmas in Canada" },
  }, 8: {
    1: { name: "Good Times with Weapons" },
    2: { name: "Up the Down Steroid" },
    3: { name: "The Passion of the Jew" },
    4: { name: "You Got F'd in the A" },
    5: { name: "Awesom-O" },
    6: { name: "The Jeffersons" },
    7: { name: "Goobacks" },
    8: { name: "Douche and Turd" },
    9: { name: "Something Wall-Mart This Way Comes" },
    10: { name: "Pre-School" },
    11: { name: "Quest for Ratings" },
    12: { name: "Stupid Spoiled Whore Video Playset" },
    13: { name: "Cartman's Incredible Gift" },
    14: { name: "Woodland Critter Christmas" },
  }, 9: {
    1: { name: "Mr. Garrison's Fancy New Vagina" },
    2: { name: "Die Hippie, Die" },
    3: { name: "Wing" },
    4: { name: "Best Friends Forever" },
    5: { name: "The Losing Edge" },
    6: { name: "The Death of Eric Cartman" },
    7: { name: "Erection Day" },
    8: { name: "Two Days Before the Day After Tomorrow" },
    9: { name: "Marjorine" },
    10: { name: "Follow That Egg!" },
    11: { name: "Ginger Kids" },
    12: { name: "Trapped in the Closet" },
    13: { name: "Free Willzyx" },
    14: { name: "Bloody Mary" },
  }, 10: {
    1: { name: "The Return of Chef" },
    2: { name: "Smug Alert!" },
    3: { name: "Cartoon Wars Part I" },
    4: { name: "Cartoon Wars Part II" },
    5: { name: "A Million Little Fibers" },
    6: { name: "ManBearPig" },
    7: { name: "Tsst" },
    8: { name: "Make Love, Not Warcraft" },
    9: { name: "Mystery of the Urinal Deuce" },
    10: { name: "Miss Teacher Bangs a Boy" },
    11: { name: "Hell on Earth 2006" },
    12: { name: "Go God Go" },
    13: { name: "Go God Go XII" },
    14: { name: "Stanley's Cup" },
  }, 11: {
    1: { name: "With Apologies to Jesse Jackson" },
    2: { name: "Cartman Sucks" },
    3: { name: "Lice Capades" },
    4: { name: "The Snuke" },
    5: { name: "Fantastic Easter Special" },
    6: { name: "D-Yikes!" },
    7: { name: "Night of the Living Homeless" },
    8: { name: "Le Petit Tourette" },
    9: { name: "More Crap" },
    10: { name: "Imaginationland Episode I" },
    11: { name: "Imaginationland Episode II" },
    12: { name: "Imaginationland Episode III" },
    13: { name: "Guitar Queer-O" },
    14: { name: "The List" },
  }, 12: {
    1: { name: "Tonsil Trouble" },
    2: { name: "Britney's New Look" },
    3: { name: "Major Boobage" },
    4: { name: "Canada on Strike" },
    5: { name: "Eek, a Penis!" },
    6: { name: "Over Logging" },
    7: { name: "Super Fun Time" },
    8: { name: "The China Probrem" },
    9: { name: "Breast Cancer Show Ever" },
    10: { name: "Pandemic" },
    11: { name: "Pandemic 2: The Startling" },
    12: { name: "About Last Night..." },
    13: { name: "Elementary School Musical" },
    14: { name: "The Ungroundable" },
  }, 13: {
    1: { name: "The Ring" },
    2: { name: "The Coon" },
    3: { name: "Margaritaville" },
    4: { name: "Eat, Pray, Queef" },
    5: { name: "Fishsticks" },
    6: { name: "Pinewood Derby" },
    7: { name: "Fatbeard" },
    8: { name: "Dead Celebrities" },
    9: { name: "Butters' Bottom Bitch" },
    10: { name: "W.T.F." },
    11: { name: "Whale Whores" },
    12: { name: "The F Word" },
    13: { name: "Dances with Smurfs" },
    14: { name: "Pee" },
  }, 14: {
    1: { name: "Sexual Healing" },
    2: { name: "The Tale of Scrotie McBoogerballs" },
    3: { name: "Medicinal Fried Chicken" },
    4: { name: "You Have 0 Friends" },
    5: { name: "200" },
    6: { name: "201" },
    7: { name: "Crippled Summer" },
    8: { name: "Poor and Stupid" },
    9: { name: "It's a Jersey Thing" },
    10: { name: "Insheeption" },
    11: { name: "Coon 2: Hindsight" },
    12: { name: "Mysterion Rises" },
    13: { name: "Coon vs. Coon and Friends" },
    14: { name: "Crème Fraîche" },
  }, 15: {
    1: { name: "HumancentiPad" },
    2: { name: "Funnybot" },
    3: { name: "Royal Pudding" },
    4: { name: "T.M.I." },
    5: { name: "Crack Baby Athletic Association" },
    6: { name: "City Sushi" },
    7: { name: "You're Getting Old" },
    8: { name: "Ass Burgers" },
    9: { name: "The Last of the Meheecans" },
    10: { name: "Bass to Mouth" },
    11: { name: "Broadway Bro Down" },
    12: { name: "1%" },
    13: { name: "A History Channel Thanksgiving" },
    14: { name: "The Poor Kid" },
  }, 16: {
    1: { name: "Reverse Cowgirl" },
    2: { name: "Cash for Gold" },
    3: { name: "Faith Hilling" },
    4: { name: "Jewpacabra" },
    5: { name: "Butterballs" },
    6: { name: "I Should Have Never Gone Ziplining" },
    7: { name: "Cartman Finds Love" },
    8: { name: "Sarcastaball" },
    9: { name: "Raising the Bar" },
    10: { name: "Insecurity" },
    11: { name: "Going Native" },
    12: { name: "A Nightmare on Face Time" },
    13: { name: "A Scause for Applause" },
    14: { name: "Obama Wins!" },
  }, 17: {
    1: { name: "Let Go, Let Gov" },
    2: { name: "Informative Murder Porn" },
    3: { name: "World War Zimmerman" },
    4: { name: "Goth Kids 3: Dawn of the Posers" },
    5: { name: "Taming Strange" },
    6: { name: "Ginger Cow" },
    7: { name: "Black Friday" },
    8: { name: "A Song of Ass and Fire" },
    9: { name: "Titties and Dragons" },
    10: { name: "The Hobbit" },
  }, 18: {
    1: { name: "Go Fund Yourself" },
    2: { name: "Gluten Free Ebola" },
    3: { name: "The Cissy" },
    4: { name: "Handicar" },
    5: { name: "The Magic Bush" },
    6: { name: "Freemium Isn't Free" },
    7: { name: "Grounded Vindaloop" },
    8: { name: "Cock Magic" },
    9: { name: "#REHASH" },
    10: { name: "#HappyHolograms" },
  }, 19: {
    1: { name: "Stunning and Brave" },
    2: { name: "Where My Country Gone?" },
    3: { name: "The City Part of Town" },
    4: { name: "You're Not Yelping" },
    5: { name: "Safe Space" },
    6: { name: "Tweek x Craig" },
    7: { name: "Naughty Ninjas" },
    8: { name: "Sponsored Content" },
    9: { name: "Truth and Advertising" },
    10: { name: "PC Principal Final Justice" },
  }
}